version: '3.8'

services:
  app:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=divino_lanches
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_NAME=Divino Lanches
      - APP_URL=${APP_URL}
      - APP_DEBUG=false
      - MULTI_TENANT_ENABLED=true
      - UPLOAD_MAX_SIZE=10M
      - ALLOWED_EXTENSIONS=jpg,jpeg,png,gif,pdf,doc,docx
    depends_on:
      - postgres
    volumes:
      - ./uploads:/var/www/html/uploads
      - ./logs:/var/www/html/logs
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=divino_lanches
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_INITDB_ARGS=--auth-local=trust --auth-host=md5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: >
      bash -c "
        if [ ! -f /var/lib/postgresql/data/PG_VERSION ]; then
          echo 'Initializing PostgreSQL database...'
          initdb -D /var/lib/postgresql/data -U postgres --auth-local=trust --auth-host=md5
          echo 'PostgreSQL initialized!'
        fi
        exec postgres -D /var/lib/postgresql/data
      "

volumes:
  postgres_data: