version: '3.8'

networks:
  divino_network:
    driver: bridge

services:
  app:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_NAME=Divino Lanches
      - APP_URL=${APP_URL}
      - APP_DEBUG=false
      - MULTI_TENANT_ENABLED=true
      - UPLOAD_MAX_SIZE=10M
      - ALLOWED_EXTENSIONS=jpg,jpeg,png,gif,pdf,doc,docx
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - WHATSAPP_ENABLED=true
      - CHATWOOT_URL=${CHATWOOT_URL}
      - CHATWOOT_API_KEY=${CHATWOOT_API_KEY}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./uploads:/var/www/html/uploads
      - ./logs:/var/www/html/logs
    networks:
      - divino_network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - divino_postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - divino_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - divino_redis_data:/data
    networks:
      - divino_network
    restart: unless-stopped


volumes:
  divino_postgres_data:
  divino_redis_data: