version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_ENV=production
      - APP_URL=${APP_URL}
      - WUZAPI_URL=http://wuzapi:8080
      - WUZAPI_API_KEY=1234ABCD
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL:-}
    depends_on:
      - postgres
      - redis
      - wuzapi
    volumes:
      - ./uploads:/var/www/html/uploads
      - ./logs:/var/www/html/logs
    networks:
      - divino-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${DB_NAME:-divino_lanches}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-divino_password}
      - POSTGRES_FORCE_INITDB=1
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - divino-network
    command: >
      bash -c "
      echo '=== FORCING POSTGRESQL INITIALIZATION ===';
      if [ -d /var/lib/postgresql/data ]; then
        echo 'Removing existing data directory...';
        rm -rf /var/lib/postgresql/data/*;
      fi;
      echo 'Starting PostgreSQL in background...';
      docker-entrypoint.sh postgres &
      echo 'Waiting for PostgreSQL to be ready...';
      while ! pg_isready -h localhost -p 5432 -U postgres; do
        echo 'PostgreSQL not ready yet, waiting...';
        sleep 2;
      done;
      echo 'PostgreSQL is ready! Creating WuzAPI user and database...';
      psql -h localhost -U postgres -d divino_lanches -c \"DROP ROLE IF EXISTS wuzapi;\";
      psql -h localhost -U postgres -d divino_lanches -c \"CREATE ROLE wuzapi WITH LOGIN CREATEDB PASSWORD 'wuzapi';\";
      psql -h localhost -U postgres -d divino_lanches -c \"DROP DATABASE IF EXISTS wuzapi;\";
      psql -h localhost -U postgres -d divino_lanches -c \"CREATE DATABASE wuzapi OWNER wuzapi;\";
      psql -h localhost -U postgres -d divino_lanches -c \"GRANT ALL PRIVILEGES ON DATABASE wuzapi TO wuzapi;\";
      echo '✅ WuzAPI user and database created successfully!';
      echo 'WuzAPI setup completed! Waiting for PostgreSQL...';
      wait;
      "


  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - divino-network

  wuzapi:
    build:
      context: ./docker/wuzapi
      dockerfile: Dockerfile
    ports:
      - "8081:8080"  # Backend Go - Externo:8081 → Interno:8080
      - "3001:3000"  # Frontend React - Externo:3001 → Interno:3000
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=wuzapi
      - DB_USER=wuzapi
      - DB_PASSWORD=wuzapi
      - WUZAPI_URL=http://wuzapi:8080
      - WEBHOOK_URL=http://app:80/webhook/wuzapi.php
      - WUZAPI_ADMIN_TOKEN=admin123456
    volumes:
      - wuzapi_sessions:/app/sessions
      - wuzapi_logs:/app/logs
      - ./wuzapi/.env:/app/.env
    depends_on:
      - postgres
    networks:
      - divino-network

volumes:
  postgres_data:
  redis_data:
  wuzapi_sessions:
  wuzapi_logs:

networks:
  divino-network:
    driver: bridge
