version: '3.8'

services:
  app:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=divino_lanches
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_NAME=Divino Lanches
      - APP_URL=${APP_URL}
      - APP_DEBUG=false
      - MULTI_TENANT_ENABLED=true
      - UPLOAD_MAX_SIZE=10M
      - ALLOWED_EXTENSIONS=jpg,jpeg,png,gif,pdf,doc,docx
    depends_on:
      - postgres
    volumes:
      - ./uploads:/var/www/html/uploads
      - ./logs:/var/www/html/logs
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data: