version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: divino-lanches-app
    ports:
      - "8080:80"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=divino_db
      - DB_USER=divino_user
      - DB_PASSWORD=divino_password
      - APP_ENV=production
      - APP_URL=http://localhost:8080
      - WUZAPI_URL=http://wuzapi:8080
      - WUZAPI_API_KEY=1234ABCD
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL:-}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./uploads:/var/www/html/uploads
      - ./logs:/var/www/html/logs
    networks:
      - divino-network

  postgres:
    image: postgres:15-alpine
    container_name: divino-lanches-db
    environment:
      - POSTGRES_DB=divino_db
      - POSTGRES_USER=divino_user
      - POSTGRES_PASSWORD=divino_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - divino-network

  redis:
    image: redis:7-alpine
    container_name: divino-lanches-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - divino-network

  wuzapi:
    build:
      context: ./docker/wuzapi
      dockerfile: Dockerfile
    container_name: divino-lanches-wuzapi
    ports:
      - "8081:8080"  # Backend Go - Externo:8081 → Interno:8080
      - "3001:3000"  # Frontend React - Externo:3001 → Interno:3000
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=wuzapi
      - DB_USER=wuzapi
      - DB_PASSWORD=wuzapi
      - WUZAPI_URL=http://wuzapi:8080  # Comunicação interna entre containers
      - WEBHOOK_URL=http://app:80/webhook/wuzapi.php
      - WUZAPI_ADMIN_TOKEN=admin123456  # Token para acesso administrativo
    volumes:
      - wuzapi_sessions:/app/sessions
      - wuzapi_logs:/app/logs
      - ./wuzapi/.env:/app/.env  # Montar arquivo .env
    depends_on:
      - postgres
    networks:
      - divino-network

volumes:
  postgres_data:
  redis_data:
  wuzapi_sessions:
  wuzapi_logs:

networks:
  divino-network:
    driver: bridge
