version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: divino-lanches-app
    ports:
      - "80:80"
    environment:
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-divino_db}
      - DB_USER=${DB_USER:-divino_user}
      - DB_PASSWORD=${DB_PASSWORD:-divino_password}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WUZAPI_URL=${WUZAPI_URL:-http://wuzapi:3000}
      - N8N_URL=${N8N_URL:-http://n8n:5678}
      - N8N_API_KEY=${N8N_API_KEY}
      - MCP_SERVER_URL=${MCP_SERVER_URL:-http://mcp-server:3100}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./uploads:/var/www/html/uploads
      - ./logs:/var/www/html/logs
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: divino-lanches-db
    environment:
      - POSTGRES_DB=${DB_NAME:-divino_db}
      - POSTGRES_USER=${DB_USER:-divino_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-divino_password}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: divino-lanches-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  wuzapi:
    build:
      context: .
      dockerfile: wuzapi/Dockerfile
    container_name: divino-lanches-wuzapi
    ports:
      - "3001:3000"
      - "8081:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://${DB_USER:-divino_user}:${DB_PASSWORD:-divino_password}@postgres:5432/${DB_NAME:-divino_db}}
    depends_on:
      - postgres
    restart: unless-stopped

  mcp-server:
    build:
      context: .
      dockerfile: n8n-mcp-server/Dockerfile
    container_name: divino-mcp-server
    ports:
      - "3100:3100"
    environment:
      - N8N_URL=${N8N_URL:-http://n8n:5678}
      - N8N_API_KEY=${N8N_API_KEY}
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: divino-lanches-n8n
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=${DB_USER:-divino_user}
      - DB_POSTGRESDB_PASSWORD=${DB_PASSWORD:-divino_password}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:5678}
      - GENERIC_TIMEZONE=America/Sao_Paulo
    depends_on:
      - postgres
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  postgres_data:
  n8n_data:
